#pragma once
#include <string>
#include <vector>

#include "pfdm_openxr_preview/openxr_yvr_private.h"
#include "pch.h"

extern PFN_xrGetSystemPropertyIntYVR xrGetSystemPropertyIntYVR;
extern PFN_xrGetSystemPropertyFloatYVR xrGetSystemPropertyFloatYVR;
extern PFN_xrGetSystemPropertyFloatArrayYVR xrGetSystemPropertyFloatArrayYVR;
extern PFN_xrGetSystemPropertyCharArrayYVR xrGetSystemPropertyCharArrayYVR;
extern PFN_xrSetSystemPropertyIntYVR xrSetSystemPropertyIntYVR;
extern PFN_xrSetSystemPropertyFloatYVR xrSetSystemPropertyFloatYVR;
extern PFN_xrSetForceHeadModeYVR xrSetForceHeadModeYVR;

extern PFN_xrStartControllerPairingYVR xrStartControllerPairingYVR;
extern PFN_xrStopControllerPairingYVR xrStopControllerPairingYVR;
extern PFN_xrRemoveControllerPairingYVR xrRemoveControllerPairingYVR;
extern PFN_xrQueryControllerPairingStateYVR xrQueryControllerPairingStateYVR;
extern PFN_xrGetControllerSerialNumberYVR xrGetControllerSerialNumberYVR;
extern PFN_xrSetPrimaryControllerHandleYVR xrSetPrimaryControllerHandleYVR;
extern PFN_xrGetPrimaryControllerHandleYVR xrGetPrimaryControllerHandleYVR;
extern PFN_xrGetControllerChargeStatusYVR xrGetControllerChargeStatusYVR;
extern PFN_xrQueryCurrentConnectedControllerTypeYVR xrQueryCurrentConnectedControllerTypeYVR;

extern PFN_xrPassthroughStartYVR xrPassthroughStartYVR;
extern PFN_xrPassthroughStopYVR xrPassthroughStopYVR;

extern PFN_xrTestBoundaryNodeYVR xrTestBoundaryNodeYVR;
extern PFN_xrTestBoundaryPointYVR xrTestBoundaryPointYVR;
extern PFN_xrGetBoundaryDimensionsYVR xrGetBoundaryDimensionsYVR;
extern PFN_xrGetBoundaryVisibleYVR xrGetBoundaryVisibleYVR;
extern PFN_xrGetBoundaryGeometryPointsCountYVR xrGetBoundaryGeometryPointsCountYVR;
extern PFN_xrGetBoundaryGeometryYVR xrGetBoundaryGeometryYVR;
extern PFN_xrGetGroundDistanceYVR xrGetGroundDistanceYVR;
extern PFN_xrGetBoundaryConfiguredYVR xrGetBoundaryConfiguredYVR;
extern PFN_xrSetBoundaryControlYVR xrSetBoundaryControlYVR;
extern PFN_xrGetBoundaryStatusYVR xrGetBoundaryStatusYVR;

extern PFN_xrGetOpenGLESGraphicsRequirementsKHR xrGetOpenGLESGraphicsRequirementsKHR;
extern PFN_xrGetVulkanGraphicsRequirements2KHR xrGetVulkanGraphicsRequirements2KHR;
extern PFN_xrSetAndroidApplicationThreadKHR xrSetAndroidApplicationThreadKHR;

extern PFN_xrEnumerateDisplayRefreshRatesFB xrEnumerateDisplayRefreshRatesFB;
extern PFN_xrGetDisplayRefreshRateFB xrGetDisplayRefreshRateFB;
extern PFN_xrRequestDisplayRefreshRateFB xrRequestDisplayRefreshRateFB;

extern PFN_xrCreateFoveationProfileFB xrCreateFoveationProfileFB;
extern PFN_xrDestroyFoveationProfileFB xrDestroyFoveationProfileFB;
extern PFN_xrUpdateSwapchainFB xrUpdateSwapchainFB;
extern PFN_xrGetSwapchainStateFB xrGetSwapchainStateFB;

extern PFN_xrGetVulkanGraphicsDevice2KHR xrGetVulkanGraphicsDevice2KHR;
extern PFN_xrGetVulkanGraphicsDeviceKHR xrGetVulkanGraphicsDeviceKHR;
extern PFN_xrCreateVulkanInstanceKHR xrCreateVulkanInstanceKHR;
extern PFN_xrCreateVulkanDeviceKHR xrCreateVulkanDeviceKHR;

extern PFN_xrCreateHandTrackerEXT xrCreateHandTrackerEXT;
extern PFN_xrDestroyHandTrackerEXT xrDestroyHandTrackerEXT;
extern PFN_xrLocateHandJointsEXT xrLocateHandJointsEXT;
extern PFN_xrGetHandMeshFB xrGetHandMeshFB;
extern PFN_xrSetCurrentInputDeviceYVR xrSetCurrentInputDeviceYVR;
extern PFN_xrGetCurrentInputDeviceYVR xrGetCurrentInputDeviceYVR;

extern PFN_xrCreateSpatialAnchorFB xrCreateSpatialAnchorFB;
extern PFN_xrGetSpaceUuidFB xrGetSpaceUuidFB;
extern PFN_xrEnumerateSpaceSupportedComponentsFB xrEnumerateSpaceSupportedComponentsFB;
extern PFN_xrSetSpaceComponentStatusFB xrSetSpaceComponentStatusFB;
extern PFN_xrGetSpaceComponentStatusFB xrGetSpaceComponentStatusFB;

extern PFN_xrQuerySpacesFB xrQuerySpacesFB;
extern PFN_xrRetrieveSpaceQueryResultsFB xrRetrieveSpaceQueryResultsFB;

extern PFN_xrSaveSpaceFB xrSaveSpaceFB;
extern PFN_xrEraseSpaceFB xrEraseSpaceFB;

extern PFN_xrCreateSpaceUserFB xrCreateSpaceUserFB;
extern PFN_xrGetSpaceUserIdFB xrGetSpaceUserIdFB;
extern PFN_xrDestroySpaceUserFB xrDestroySpaceUserFB;

extern PFN_xrShareSpacesFB xrShareSpacesFB;

extern PFN_xrSaveSpaceListFB xrSaveSpaceListFB;

extern PFN_xrCreatePlaneDetectorEXT xrCreatePlaneDetectorEXT;
extern PFN_xrDestroyPlaneDetectorEXT xrDestroyPlaneDetectorEXT;
extern PFN_xrBeginPlaneDetectionEXT xrBeginPlaneDetectionEXT;
extern PFN_xrGetPlaneDetectionStateEXT xrGetPlaneDetectionStateEXT;
extern PFN_xrGetPlaneDetectionsEXT xrGetPlaneDetectionsEXT;
extern PFN_xrGetPlanePolygonBufferEXT xrGetPlanePolygonBufferEXT;

extern PFN_xrCreateEyeTrackerFB xrCreateEyeTrackerFB;
extern PFN_xrDestroyEyeTrackerFB xrDestroyEyeTrackerFB;
extern PFN_xrGetEyeGazesFB xrGetEyeGazesFB;

extern PFN_xrGetSpaceBoundingBox2DFB xrGetSpaceBoundingBox2DFB;
extern PFN_xrGetSpaceBoundingBox3DFB xrGetSpaceBoundingBox3DFB;
extern PFN_xrGetSpaceSemanticLabelsFB xrGetSpaceSemanticLabelsFB;
extern PFN_xrGetSpaceBoundary2DFB xrGetSpaceBoundary2DFB;
extern PFN_xrGetSpaceRoomLayoutFB xrGetSpaceRoomLayoutFB;
extern PFN_xrGetSpaceContainerFB xrGetSpaceContainerFB;
extern PFN_xrRequestSceneCaptureFB xrRequestSceneCaptureFB;

extern PFN_xrSetSpaceBoundingBox2DYVR xrSetSpaceBoundingBox2DYVR;
extern PFN_xrSetSpaceBoundingBox3DYVR xrSetSpaceBoundingBox3DYVR;
extern PFN_xrSetSpaceSemanticLabelsYVR xrSetSpaceSemanticLabelsYVR;
extern PFN_xrSetSpaceBoundary2DYVR xrSetSpaceBoundary2DYVR;
extern PFN_xrSetSpaceRoomLayoutYVR xrSetSpaceRoomLayoutYVR;
extern PFN_xrSetSpaceContainerYVR xrSetSpaceContainerYVR;
extern PFN_xrResetSceneYVR xrResetSceneYVR;
extern PFN_xrGetSceneStatusYVR xrGetSceneStatusYVR;
extern PFN_xrSetLocateRoomYVR xrSetLocateRoomYVR;
extern PFN_xrGetLocateRoomYVR xrGetLocateRoomYVR;
extern PFN_xrGetSpaceTriangleMeshMETA xrGetSpaceTriangleMeshMETA;

extern PFN_xrGetRecommendedResolution xrGetRecommendedResolution;

extern PFN_xrCreateSwapchainAndroidSurfaceKHR xrCreateSwapchainAndroidSurfaceKhr;

extern PFN_xrCreateMeshDetectorYVR xrCreateMeshDetectorYVR;
extern PFN_xrDestroyMeshDetectorYVR xrDestroyMeshDetectorYVR;
extern PFN_xrBeginRoomSetupYVR xrBeginRoomSetupYVR;
extern PFN_xrEndRoomSetupYVR xrEndRoomSetupYVR;
extern PFN_xrSetSpaceTriangleMeshYVR xrSetSpaceTriangleMeshYVR;
extern PFN_xrBeginBoundaryDetectYVR xrBeginBoundaryDetectYVR;
extern PFN_xrEndBoundaryDetectYVR xrEndBoundaryDetectYVR;


extern PFN_xrCreatePassthroughProviderYVR xrCreatePassthroughProviderYVR;
extern PFN_xrDestroyPassthroughProviderYVR xrDestroyPassthroughProviderYVR;
extern PFN_xrStartPassthroughProviderYVR xrStartPassthroughProviderYVR;
extern PFN_xrStopPassthroughProviderYVR xrStopPassthroughProviderYVR;
extern PFN_xrCreatePassthroughSwapchainYVR xrCreatePassthroughSwapchainYVR;
extern PFN_xrDestroyPassthroughSwapchainYVR xrDestroyPassthroughSwapchainYVR;
extern PFN_xrEnumeratePassthroughSwapchainImagesYVR xrEnumeratePassthroughSwapchainImagesYVR;
extern PFN_xrAcquirePassthroughImageYVR xrAcquirePassthroughImageYVR;
extern PFN_xrCreatePassthroughSwapchainYVR2 xrCreatePassthroughSwapchainYVR2;

extern PFN_xrSetColorSpaceYVR xrSetColorSpaceYVR;
extern PFN_xrSetColorSpaceFB xrSetColorSpaceFB;

extern PFN_xrSetLargeSpaceMapRecordEnableYVR xrSetLargeSpaceMapRecordEnableYVR;
extern PFN_xrSetMarkerDetectionEnableYVR xrSetMarkerDetectionEnableYVR;
extern PFN_xrClearAllMarkersYVR xrClearAllMarkersYVR;
extern PFN_xrSetLargeSpaceOriginPoseYVR xrSetLargeSpaceOriginPoseYVR;
extern PFN_xrExportLargeSpaceMapYVR xrExportLargeSpaceMapYVR;
extern PFN_xrSetRecenterEnableYVR xrSetRecenterEnableYVR;
extern PFN_xrGetRecenterEnableYVR xrGetRecenterEnableYVR;
extern PFN_xrSetLargeSpaceMapAssemblingEnableYVR xrSetLargeSpaceMapAssemblingEnableYVR;
extern PFN_xrGetLargeSpacePointsCalibParamsYVR xrGetLargeSpacePointsCalibParamsYVR;

extern PFN_xrStartHandCalibrationYVR xrStartHandCalibrationYVR;
extern PFN_xrRegisterHandEventCallbackYVR xrRegisterHandEventCallbackYVR;
extern PFN_xrUnregisterHandEventCallbackYVR xrUnregisterHandEventCallbackYVR;
extern PFN_xrStopHandCalibrationYVR xrStopHandCalibrationYVR;


extern PFN_xrSetSlamCalibrationEnableYVR xrSetSlamCalibrationEnableYVR;

extern PFN_xrGetPlaneDetectionsYVR xrGetPlaneDetectionsYVR;
extern PFN_xrGetPlanePolygonBufferYVR xrGetPlanePolygonBufferYVR;

extern PFN_xrGetRenderScaleYVR xrGetRenderScaleYVR;
extern PFN_xrSetRenderScaleYVR xrSetRenderScaleYVR;
extern PFN_xrGetRenderSharpenYVR xrGetRenderSharpenYVR;
extern PFN_xrSetRenderSharpenYVR xrSetRenderSharpenYVR;
extern PFN_xrGetRenderFovYVR xrGetRenderFovYVR;
extern PFN_xrSetRenderFovYVR xrSetRenderFovYVR;
extern PFN_xrResetRenderFovYVR xrResetRenderFovYVR;
extern PFN_xrGetColorSpaceConfigYVR xrGetColorSpaceConfigYVR;
extern PFN_xrSetColorSpaceConfigYVR xrSetColorSpaceConfigYVR;

extern PFN_xrConvertTimespecTimeToTimeKHR xrConvertTimespecTimeToTimeKHR;

extern PFN_xrSetImageTrackingYVR xrSetImageTrackingYVR;
extern PFN_xrRegisterImageTemplateYVR xrRegisterImageTemplateYVR;
extern PFN_xrUnRegisterImageTemplateYVR xrUnRegisterImageTemplateYVR;
extern PFN_xrCreateImageSpaceYVR xrCreateImageSpaceYVR;

extern PFN_xrCreatePassthroughFB xrCreatePassthroughFB;
extern PFN_xrDestroyPassthroughFB xrDestroyPassthroughFB;
extern PFN_xrPassthroughStartFB xrPassthroughStartFB;
extern PFN_xrPassthroughPauseFB xrPassthroughPauseFB;
extern PFN_xrCreatePassthroughLayerFB xrCreatePassthroughLayerFB;
extern PFN_xrDestroyPassthroughLayerFB xrDestroyPassthroughLayerFB;
extern PFN_xrPassthroughLayerPauseFB xrPassthroughLayerPauseFB;
extern PFN_xrPassthroughLayerResumeFB xrPassthroughLayerResumeFB;
extern PFN_xrPassthroughLayerSetStyleFB xrPassthroughLayerSetStyleFB;
extern PFN_xrCreatePassthroughColorLutMETA xrCreatePassthroughColorLutMETA;
extern PFN_xrDestroyPassthroughColorLutMETA xrDestroyPassthroughColorLutMETA;
extern PFN_xrUpdatePassthroughColorLutMETA xrUpdatePassthroughColorLutMETA;

extern PFN_xrGetDPCompostionStateYVR xrGetDPCompositionStateYVR;
extern PFN_xrStartDPCompostionYVR xrStartDPCompositionYVR;
extern PFN_xrStopDPCompostionYVR xrStopDPCompositionYVR;

extern PFN_xrSetPersistentPassthroughMeshModeInfoYVR xrSetPersistentPassthroughMeshModeInfoYVR;
extern PFN_xrGetPersistentPassthroughMeshModeInfoYVR xrGetPersistentPassthroughMeshModeInfoYVR;
extern PFN_xrSetPersistentPassthroughMeshYVR xrSetPersistentPassthroughMeshYVR;
extern PFN_xrSetPersistentPassthroughMeshTransformYVR xrSetPersistentPassthroughMeshTransformYVR;

class OpenXRExtMgr
{
public:
    void initExtensions();
    std::vector<std::string> getInstanceExtensions();
    float getFloatProperty(const xrGetSystemPropertyYVR& property);
    void getFloatArrayProperty(const xrGetSystemPropertyYVR& property, float* array, int dataLength);
    void getCharArrayProperty(const xrGetSystemPropertyYVR& property, char* array, int dataLength);
    int getIntProperty(const xrGetSystemPropertyYVR& property);

    bool isEnableTargetExt(string ext);
    void setFloatProperty(const xrSetSystemPropertyYVR& property, float value);

private:
    std::vector<std::string> enabledExtensions{};
};
